### ISSUE TITLE
Linter beanstandet Umlaute in Texten und Strings

### ISSUE THREAD

**Issue by acousma82** [ikuseiGmbH/linters#8]
Wenn Umlaute im Code benutzt werden sagt der Linter:

message: 'invalid multibyte char (US-ASCII)'

Der Cop dafür muss im Yaml gefunden werden und im Gem entsprechend ausgeschaltet werden.

**Comment by acousma82** [comment]
Die Beanstandung der Umlaute kam vom Ruby plugin in vscode. Linter ist ok. Lösung ist dies in den vscode Einstellungen auszuschalten.

**Comment by 5minpause** [comment]
Es gibt (trotzdem) einen Cop => [Style/AsciiComments](http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/AsciiComments), der dafuer zustaendig ist und entsprechend de-/aktiviert werden kann. (Existiert seit Version 0.54.0)

**Comment by acousma82** [comment]
Ja den haben wir auch aktiviert, es geht aber um Umlaute in Springs im Coe und nicht in Kommentaren.

**Comment by acousma82** [comment]
Also bzw. deaktiviert.

**Comment by donni106** [comment]
Siehe hier: https://github.com/ikuseiGmbH/linters/blob/with_installer/rubocop.yml#L800-L802

```
Style/AsciiComments:
  Enabled: false
  AllowedChars: []
```
